### ISSUE TITLE
Exception for `-webkit-tap-highlight-color: rgba(0,0,0,0);`

### ISSUE THREAD

**Issue by pytkin** [ben-eb/colormin#1]
Input:

``` css
-webkit-tap-highlight-color: rgba(0,0,0,0);
```

Output:

``` css
-webkit-tap-highlight-color: transparent;
```

**Comment by ben-eb** [comment]
These values are equivalent, are they not? `transparent` is equivalent to `rgba(0,0,0,0)`.

This tracker is not the right place for this discussion. You probably want https://github.com/ben-eb/postcss-colormin
